python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_ads.txt -cand data/candidates/atf/ads/atf_ads_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/ads -rank all -o -se search -mp 1 > log/ads_1.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_ads.txt -cand data/candidates/atf/ads/atf_ads_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/ads -rank all -o -se search -mp 2 > log/ads_2.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_ads.txt -cand data/candidates/atf/ads/atf_ads_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/ads -rank all -o -se search -mp 3 > log/ads_3.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_ads.txt -cand data/candidates/atf/ads/atf_ads_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/ads -rank all -o -se search -mp 4 > log/ads_4.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_ads.txt -cand data/candidates/atf/ads/atf_ads_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/ads -rank all -o -se search -mp 5 > log/ads_5.txt

python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_market.txt -cand data/candidates/atf/market/atf_market_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt  -out data/evaluation/atf/market -rank all -o  -se search -mp 1 > log/market_1.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_market.txt -cand data/candidates/atf/market/atf_market_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt  -out data/evaluation/atf/market -rank all -o  -se search -mp 2 > log/market_2.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_market.txt -cand data/candidates/atf/market/atf_market_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt  -out data/evaluation/atf/market -rank all -o  -se search -mp 3 > log/market_3.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_market.txt -cand data/candidates/atf/market/atf_market_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt  -out data/evaluation/atf/market -rank all -o  -se search -mp 4 > log/market_4.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_market.txt -cand data/candidates/atf/market/atf_market_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt  -out data/evaluation/atf/market -rank all -o  -se search -mp 5 > log/market_5.txt

python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_forums.txt -cand data/candidates/atf/forum/atf_forums_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/forum -rank all -o  -se search -mp 1 > log/forum_1.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_forums.txt -cand data/candidates/atf/forum/atf_forums_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/forum -rank all -o  -se search -mp 2 > log/forum_2.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_forums.txt -cand data/candidates/atf/forum/atf_forums_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/forum -rank all -o  -se search -mp 3 > log/forum_3.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_forums.txt -cand data/candidates/atf/forum/atf_forums_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/forum -rank all -o  -se search -mp 4 > log/forum_4.txt
#python evaluation/evaluate.py -re body -seed data/seeds/atf/atf_forums.txt -cand data/candidates/atf/forum/atf_forums_candidates.txt -neg data/candidates/dmoz/negative_dmoz_sites.txt -out data/evaluation/atf/forum -rank all -o  -se search -mp 5 > log/forum_5.txt
